name: cancelable_retry
description: Utility for wrapping an asynchronous function in automatic retry logic with ability to cancel it.
version: 0.1.0
homepage: https://github.com/innim/
repository: https://github.com/Innim/dart_cancelable_retry
issue_tracker: https://github.com/Innim/dart_cancelable_retry/issues

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies: 
  async: any

dev_dependencies:
  innim_lint: ^0.1.3
  test: ^1.16.0
